image: alpine:latest

stages:
  - publish

pages:
  image: gitlab.devpizzasoft.ru:4567/root/public-containers/node:12.13.1-slim
  stage: publish
  only:
  - master
  script:
  - npm i
  - npm run build
  artifacts:
    paths:
    - public
  
